[Common]
;select an image to display as background
BgImage=launcher_bg.jpg
BgColor=0,0,0
;window size
WindowWidth=600
WindowHeight=300
; Sounds
BackgroundSound=ambient.mp3
ButtonSound=click.wav
; Loop ambient music
LoopBackground=1

;This will auto start the game at button0
[Timer]
Timeout=5
Font=Courier New
FontSize=12
Color=24,255,3
TextRunning=Initiating in %ds...
TextPaused=PAUSED: Waiting for input...
X=30
Y=265

[Button0]
Text=[ PLAY GAME ]
Key=P
Font=Impact
FontSize=14
Color=24,255,3
HoverColor=255,255,255
Command=Fallout3.exe
X=380
Y=50

[Button1]
Text=[ F.O.S.E. ]
Key=D
Font=Courier New
FontSize=14
Color=24,255,3
HoverColor=255,255,255
Command=fose_loader.exe
X=380
Y=100

[Button2]
Text=[ SETTINGS ]
Key=S
Font=Courier New
FontSize=14
Color=24,255,3
HoverColor=255,255,255
Command=notepad.exe launcher.ini
X=380
Y=150

[Button3]
Text=[ TOOLS ]
Key=T
Font=Courier New
FontSize=14
Color=24,255,3
HoverColor=255,255,255
Command=Geck.exe
X=380
Y=200

[Button4]
Text=[ EXIT ]
Key=X
Font=Courier New
FontSize=14
Color=24,255,3
HoverColor=255,255,255
Command=EXIT
X=380
Y=250
